# Generated by Django 3.1 on 2020-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPR', '0002_remove_recipes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
